ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    LEARNER=bhanu" \
    DURATION="10HRS" \
    AUTHOR="joindevops"
RUN echo "Learner is: ${LEARNER}, version is: ${version}"
CMD ["sleep", "200"]